print("siign  up enter your information down")
name=  input("enter name:")
surname= input("enter surname:")
age =int(input("enter age:"))
email= input("enter amail:")
birt_year= (input("enter birth year:"))
birt_month=(input("enter birt month:"))
birt_day= (input("enter birthday:"))
dot= ("/")
print("name=",name)
print("surname=",surname)
print("age=",age)
print("email=",email)
print("birthdate=",birt_day+dot+birt_month+dot+birt_year)